version: 2
jobs:
  build:
    docker:
      - image: hborawski/swift-docc-docker:sha-fa2a2c1

    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p .build/symbol-graphs
            rm -rf .build/symbol-graphs/* || true
            swift build --target SwiftHooks \
                -Xswiftc -emit-symbol-graph \
                -Xswiftc -emit-symbol-graph-dir -Xswiftc .build/symbol-graphs
            mkdir .build/swift-docc-symbol-graphs
            rm -rf .build/swift-docc-symbol-graphs/* || true
            mv .build/symbol-graphs/SwiftHooks* .build/swift-docc-symbol-graphs/
      - run:
          name: Test
          command: |
            mkdir -p .build/reports
            swift test --parallel --enable-code-coverage --xunit-output=.build/reports/junit.xml
            BIN_PATH="$(swift build --show-bin-path)"
            XCTEST_PATH="$(find ${BIN_PATH} -name '*.xctest')"
            COV_BIN=$XCTEST_PATH
            llvm-cov export \
              --instr-profile=.build/debug/codecov/default.profdata \
              --ignore-filename-regex=".build|Tests|ExampleLibrary" \
              --format=lcov \
              "${COV_BIN}" \
              > .build/reports/coverage.lcov
      - run:
          name: Docs
          command: |
            swift run docc convert Sources/SwiftHooks/Documentation.docc \
              --fallback-display-name SwiftHooks \
              --fallback-bundle-identifier com.intuit.hooks \
              --additional-symbol-graph-dir .build/swift-docc-symbol-graphs \
              --output-path SwiftHooks.doccarchive

            swift run docc process-archive transform-for-static-hosting --hosting-base-path swift-hooks SwiftHooks.doccarchive
      - run:
          name: Upload CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
      - store_test_results:
          path: .build/reports/
      - persist_to_workspace:
          root: .
          paths:
            - SwiftHooks.doccarchive

  release:
    docker:
      - image: hborawski/auto-container:sha-767eebf

    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -r /tmp/workspace/SwiftHooks.doccarchive .
      - run: 
          name: Git Config
          command: |
            echo "https://$GITHUB_USER:$GH_TOKEN@github.intuit.com" >> /tmp/gitcredfile
            git config --global user.name "$GITHUB_USER"
            git config --global user.email "opensource-svc@intuit.com"
            git config --global credential.helper "store --file=/tmp/gitcredfile"
      - run: ~/auto shipit -vvv
workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          requires:
            - build