version: 2
jobs:
  build:
    docker:
      - image: hborawski/swift-docc-docker:latest

    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p .build/symbol-graphs
            rm -rf .build/symbol-graphs/* || true
            swift build --target SwiftHooks \
                -Xswiftc -emit-symbol-graph \
                -Xswiftc -emit-symbol-graph-dir -Xswiftc .build/symbol-graphs
            mkdir .build/swift-docc-symbol-graphs
            rm -rf .build/swift-docc-symbol-graphs/* || true
            mv .build/symbol-graphs/SwiftHooks* .build/swift-docc-symbol-graphs/
      - run:
          name: Test
          command: |
            mkdir -p .build/reports
            swift test --parallel --enable-code-coverage --xunit-output=.build/reports/junit.xml
            BIN_PATH="$(swift build --show-bin-path)"
            XCTEST_PATH="$(find ${BIN_PATH} -name '*.xctest')"
            COV_BIN=$XCTEST_PATH
            llvm-cov export \
              --instr-profile=.build/debug/codecov/default.profdata \
              --ignore-filename-regex=".build|Tests|ExampleLibrary" \
              --format=lcov \
              "${COV_BIN}" \
              > .build/reports/coverage.lcov
      - run:
          name: Docs
          command: |
            swift run docc convert Sources/SwiftHooks/Documentation.docc \
              --fallback-display-name SwiftHooks \
              --fallback-bundle-identifier com.intuit.hooks \
              --additional-symbol-graph-dir .build/swift-docc-symbol-graphs \
              --output-path SwiftHooks.doccarchive \
              --hosting-base-path swift-hooks

            swift run docc process-archive transform-for-static-hosting SwiftHooks.doccarchive
      - store_test_results:
          path: .build/reports/
      - store_artifacts:
          path: .build/reports/

  release:
    docker:
      - image: hborawski/swift-docc-docker:latest

    steps:
      - checkout
      - run: whoami
      - run: echo $PATH
      - run: rbenv rehash
      - run: which pod
      - run: ~/auto shipit -vvv --dry-run
workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          requires:
            - build